name: 'The BOSS Way!'
favicon: null
layout_spectrum: 0.98522
typography_spectrum: 0.36523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6d5ff'
    - '#000000'
    - '#099cc2'
    - '#1f00c2'
    - '#6b6a85'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
