name: 'The BOSS Way!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0179d0'
    - '#00d3ff'
    - '#91211f'
    - '#131a2a'
    - '#f6f8f9'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
