name: 'The BOSS Way!'
favicon: null
layout_spectrum: 0.49226
typography_spectrum: 0.26331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01fafe'
    - '#020028'
    - '#96674b'
    - '#caf2f4'
    - '#d0a755'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
