name: 'The BOSS Way!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#02518c'
    - '#b52026'
    - '#a9c938'
    - '#009fbd'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
