name: 'The BOSS Way!'
favicon: null
layout_spectrum: 0.24877
typography_spectrum: 0.60391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aee1f4'
    - '#010a11'
    - '#645443'
    - '#718b91'
    - '#c9743e'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
