typography_spectrum: 0.85643
color:
  brandColors:
    - '#569ca8'
    - '#1f2348'
    - '#73eee1'
    - '#fda68a'
    - '#de1d8a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50247
analytics:
  google: null
  facebook: null
  twitter: null
name: The BOSS Way!
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
