name: 'The BOSS Way!'
favicon: null
layout_spectrum: 0.98522
typography_spectrum: 0.85643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#062b3d'
    - '#0c828f'
    - '#74cddf'
    - '#c9e8f2'
    - '#63a0b3'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
